USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;
USE WAREHOUSE RFR_WH;

CREATE OR REPLACE VIEW RISK_CASE_OVERVIEW AS
SELECT
    f.FINDING_ID,
    f.CUSTOMER_ID,
    f.ACCOUNT_ID,

    c.CUSTOMER_NAME,
    c.COUNTRY AS CUSTOMER_COUNTRY,
    c.CUSTOMER_TYPE,
    c.CUSTOMER_RISK_LEVEL,
    c.ANNUAL_INCOME,
    c.KYC_STATUS,
    c.PEP_FLAG,

    a.ACCOUNT_TYPE,
    a.CURRENCY,
    a.BALANCE,
    a.STATUS AS ACCOUNT_STATUS,

    f.FINDING_TYPE,
    f.RISK_LEVEL,
    f.RISK_SCORE,
    f.SIGNAL_COUNT,
    f.SIGNAL_TYPES,

    f.FINDING_TITLE,
    f.FINDING_SUMMARY,
    f.RECOMMENDED_ACTION,
    f.STATUS AS FINDING_STATUS,
    f.CREATED_AT

FROM RISK_FINDINGS f

LEFT JOIN RAW.CUSTOMERS c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID

LEFT JOIN RAW.ACCOUNTS a
    ON f.ACCOUNT_ID = a.ACCOUNT_ID;


CREATE OR REPLACE VIEW RISK_SIGNAL_EVIDENCE AS
SELECT
    rs.SIGNAL_ID,
    rs.CUSTOMER_ID,
    rs.ACCOUNT_ID,
    rs.TRANSACTION_ID,

    rs.SIGNAL_TYPE,
    rs.SIGNAL_SEVERITY,
    rs.SIGNAL_SCORE,
    rs.DETECTED_AT,
    rs.EVIDENCE AS SIGNAL_EVIDENCE,

    t.TRANSACTION_TIMESTAMP,
    t.AMOUNT,
    t.CURRENCY,
    t.TRANSACTION_TYPE,
    t.CHANNEL,
    t.MERCHANT,
    t.COUNTRY AS TRANSACTION_COUNTRY,

    c.COUNTRY AS CUSTOMER_HOME_COUNTRY,
    c.CUSTOMER_TYPE,
    c.CUSTOMER_RISK_LEVEL

FROM RISK_SIGNALS rs

LEFT JOIN RAW.TRANSACTIONS t
    ON rs.TRANSACTION_ID = t.TRANSACTION_ID

LEFT JOIN RAW.CUSTOMERS c
    ON rs.CUSTOMER_ID = c.CUSTOMER_ID;


SELECT
    FINDING_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    RISK_LEVEL,
    RISK_SCORE,
    SIGNAL_COUNT,
    SIGNAL_TYPES,
    FINDING_SUMMARY,
    RECOMMENDED_ACTION
FROM ANALYTICS.RISK_CASE_OVERVIEW
WHERE CUSTOMER_ID = 'C00506';


SELECT
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    TRANSACTION_TIMESTAMP,
    AMOUNT,
    TRANSACTION_COUNTRY,
    SIGNAL_EVIDENCE
FROM ANALYTICS.RISK_SIGNAL_EVIDENCE
WHERE CUSTOMER_ID = 'C00506'
ORDER BY TRANSACTION_TIMESTAMP;


DESC SEMANTIC VIEW RFR_COPILOT.ANALYTICS.RISK_INTELLIGENCE;


USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;
USE WAREHOUSE RFR_WH;

CREATE OR REPLACE VIEW INVESTIGATION_SIGNAL_EVIDENCE AS
SELECT
    f.FINDING_ID,

    rs.SIGNAL_ID,
    rs.CUSTOMER_ID,
    rs.ACCOUNT_ID,
    rs.TRANSACTION_ID,

    rs.SIGNAL_TYPE,
    rs.SIGNAL_SEVERITY,
    rs.SIGNAL_SCORE,
    rs.DETECTED_AT,
    rs.EVIDENCE AS SIGNAL_EVIDENCE,

    t.TRANSACTION_TIMESTAMP,
    t.AMOUNT,
    t.CURRENCY,
    t.TRANSACTION_TYPE,
    t.CHANNEL,
    t.MERCHANT,
    t.COUNTRY AS TRANSACTION_COUNTRY,

    c.COUNTRY AS CUSTOMER_HOME_COUNTRY

FROM RISK_SIGNALS rs

JOIN RISK_FINDINGS f
    ON rs.CUSTOMER_ID = f.CUSTOMER_ID
   AND rs.ACCOUNT_ID = f.ACCOUNT_ID

LEFT JOIN RFR_COPILOT.RAW.TRANSACTIONS t
    ON rs.TRANSACTION_ID = t.TRANSACTION_ID

LEFT JOIN RFR_COPILOT.RAW.CUSTOMERS c
    ON rs.CUSTOMER_ID = c.CUSTOMER_ID;


SELECT
    FINDING_ID,
    SIGNAL_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    TRANSACTION_TIMESTAMP,
    AMOUNT,
    TRANSACTION_COUNTRY,
    SIGNAL_EVIDENCE
FROM INVESTIGATION_SIGNAL_EVIDENCE
WHERE CUSTOMER_ID = 'C00506'
ORDER BY TRANSACTION_TIMESTAMP;


CREATE OR ALTER SEMANTIC VIEW RFR_COPILOT.ANALYTICS.RISK_INTELLIGENCE

TABLES (

    investigation AS RFR_COPILOT.ANALYTICS.INVESTIGATION_DATA
        PRIMARY KEY (FINDING_ID),

    signal_evidence AS RFR_COPILOT.ANALYTICS.INVESTIGATION_SIGNAL_EVIDENCE
        PRIMARY KEY (SIGNAL_ID)
)

RELATIONSHIPS (

    investigation_to_signal_evidence AS
        signal_evidence (FINDING_ID)
        REFERENCES investigation
)

FACTS (

    investigation.ACCOUNT_BALANCE AS investigation.BALANCE,
    investigation.ANNUAL_INCOME AS investigation.ANNUAL_INCOME,
    investigation.RISK_SCORE AS investigation.RISK_SCORE,
    investigation.SIGNAL_COUNT AS investigation.SIGNAL_COUNT,

    signal_evidence.TRANSACTION_AMOUNT AS signal_evidence.AMOUNT,
    signal_evidence.SIGNAL_SCORE AS signal_evidence.SIGNAL_SCORE
)

DIMENSIONS (

    investigation.CUSTOMER_ID_DIM AS investigation.CUSTOMER_ID,
    investigation.CUSTOMER_NAME_DIM AS investigation.CUSTOMER_NAME,
    investigation.HOME_COUNTRY_DIM AS investigation.CUSTOMER_HOME_COUNTRY,
    investigation.CUSTOMER_TYPE_DIM AS investigation.CUSTOMER_TYPE,
    investigation.CUSTOMER_RISK_DIM AS investigation.CUSTOMER_RISK_LEVEL,
    investigation.ACCOUNT_ID_DIM AS investigation.ACCOUNT_ID,
    investigation.ACCOUNT_TYPE_DIM AS investigation.ACCOUNT_TYPE,
    investigation.CURRENCY_DIM AS investigation.CURRENCY,
    investigation.FINDING_TYPE_DIM AS investigation.FINDING_TYPE,
    investigation.RISK_LEVEL_DIM AS investigation.RISK_LEVEL,
    investigation.SIGNAL_TYPES_DIM AS investigation.SIGNAL_TYPES,
    investigation.KYC_STATUS_DIM AS investigation.KYC_STATUS,

    signal_evidence.SIGNAL_ID_DIM AS signal_evidence.SIGNAL_ID,
    signal_evidence.CUSTOMER_ID_DIM AS signal_evidence.CUSTOMER_ID,
    signal_evidence.ACCOUNT_ID_DIM AS signal_evidence.ACCOUNT_ID,
    signal_evidence.TRANSACTION_ID_DIM AS signal_evidence.TRANSACTION_ID,
    signal_evidence.SIGNAL_TYPE_DIM AS signal_evidence.SIGNAL_TYPE,
    signal_evidence.SIGNAL_SEVERITY_DIM AS signal_evidence.SIGNAL_SEVERITY,
    signal_evidence.TRANSACTION_COUNTRY_DIM AS signal_evidence.TRANSACTION_COUNTRY,
    signal_evidence.CUSTOMER_HOME_COUNTRY_DIM AS signal_evidence.CUSTOMER_HOME_COUNTRY,
    signal_evidence.TRANSACTION_TYPE_DIM AS signal_evidence.TRANSACTION_TYPE,
    signal_evidence.CHANNEL_DIM AS signal_evidence.CHANNEL,
    signal_evidence.MERCHANT_DIM AS signal_evidence.MERCHANT,
    signal_evidence.SIGNAL_EVIDENCE_DIM AS signal_evidence.SIGNAL_EVIDENCE,
    signal_evidence.TRANSACTION_TIMESTAMP_DIM AS signal_evidence.TRANSACTION_TIMESTAMP
);


DESC SEMANTIC VIEW RFR_COPILOT.ANALYTICS.RISK_INTELLIGENCE;

SELECT *
FROM SEMANTIC_VIEW(
    RFR_COPILOT.ANALYTICS.RISK_INTELLIGENCE
    DIMENSIONS
        investigation.CUSTOMER_ID_DIM,
        investigation.ACCOUNT_ID_DIM,
        signal_evidence.TRANSACTION_ID_DIM,
        signal_evidence.SIGNAL_TYPE_DIM,
        signal_evidence.SIGNAL_SEVERITY_DIM,
        signal_evidence.TRANSACTION_COUNTRY_DIM
    WHERE investigation.CUSTOMER_ID_DIM = 'C00506'
);