USE DATABASE RFR_COPILOT;
USE SCHEMA RAW;
USE WAREHOUSE RFR_WH;

INSERT INTO CUSTOMERS (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNTRY,
    CUSTOMER_TYPE,
    CUSTOMER_RISK_LEVEL,
    ANNUAL_INCOME,
    CUSTOMER_SINCE,
    KYC_STATUS,
    PEP_FLAG
)
VALUES
('C00102','Customer_102','Singapore','SME','LOW',
 3399465,'2022-06-08','VERIFIED',FALSE),

('C00203','Customer_203','Singapore','PREMIUM','LOW',
 4496183,'2023-08-07','PENDING',FALSE),

('C00304','Customer_304','Germany','SME','LOW',
 1775860,'2019-02-10','VERIFIED',FALSE),

('C00405','Customer_405','Germany','PREMIUM','LOW',
 2535667,'2020-02-19','VERIFIED',FALSE),

('C00506','Customer_506','Germany','PREMIUM','LOW',
 2833820,'2025-02-19','VERIFIED',FALSE);

 INSERT INTO CUSTOMERS (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNTRY,
    CUSTOMER_TYPE,
    CUSTOMER_RISK_LEVEL,
    ANNUAL_INCOME,
    CUSTOMER_SINCE,
    KYC_STATUS,
    PEP_FLAG
)
SELECT
    'C' || LPAD(1000 + ROW_NUMBER() OVER (ORDER BY SEQ4()), 5, '0')
        AS CUSTOMER_ID,

    'Customer_' ||
        (1000 + ROW_NUMBER() OVER (ORDER BY SEQ4()))
        AS CUSTOMER_NAME,

    CASE UNIFORM(1,5,RANDOM())
        WHEN 1 THEN 'India'
        WHEN 2 THEN 'Singapore'
        WHEN 3 THEN 'Germany'
        WHEN 4 THEN 'United Kingdom'
        ELSE 'United Arab Emirates'
    END AS COUNTRY,

    CASE UNIFORM(1,3,RANDOM())
        WHEN 1 THEN 'RETAIL'
        WHEN 2 THEN 'SME'
        ELSE 'PREMIUM'
    END AS CUSTOMER_TYPE,

    CASE
        WHEN UNIFORM(1,100,RANDOM()) <= 5 THEN 'HIGH'
        WHEN UNIFORM(1,100,RANDOM()) <= 20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS CUSTOMER_RISK_LEVEL,

    ROUND(
        UNIFORM(30000,5000000,RANDOM()),
        2
    ) AS ANNUAL_INCOME,

    DATEADD(
        DAY,
        -UNIFORM(30,2500,RANDOM()),
        CURRENT_DATE()
    ) AS CUSTOMER_SINCE,

    CASE
        WHEN UNIFORM(1,100,RANDOM()) <= 8 THEN 'PENDING'
        ELSE 'VERIFIED'
    END AS KYC_STATUS,

    CASE
        WHEN UNIFORM(1,100,RANDOM()) <= 2 THEN TRUE
        ELSE FALSE
    END AS PEP_FLAG

FROM TABLE(GENERATOR(ROWCOUNT => 495));

SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM CUSTOMERS;

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID IN
(
    'C00102',
    'C00203',
    'C00304',
    'C00405',
    'C00506'
)
ORDER BY CUSTOMER_ID;