USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE RISK_SIGNALS (
    SIGNAL_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(20),
    ACCOUNT_ID VARCHAR(20),
    TRANSACTION_ID VARCHAR(30),

    SIGNAL_TYPE VARCHAR(50),
    SIGNAL_SEVERITY VARCHAR(20),
    SIGNAL_SCORE NUMBER(5,2),

    DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    EVIDENCE VARCHAR(2000)
);

/* 
We'll flag customers with 5+ transactions within 15 minutes. */

INSERT INTO ANALYTICS.RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH velocity AS (
    SELECT
        t.CUSTOMER_ID,
        t.ACCOUNT_ID,
        t.TRANSACTION_ID,
        t.TRANSACTION_TIMESTAMP,
        COUNT(*) OVER (
            PARTITION BY t.CUSTOMER_ID
            ORDER BY t.TRANSACTION_TIMESTAMP
            RANGE BETWEEN INTERVAL '15 MINUTE' PRECEDING
                      AND CURRENT ROW
        ) AS TX_COUNT
    FROM RAW.TRANSACTIONS t
)

SELECT
    'VEL_' || TRANSACTION_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    'TRANSACTION_VELOCITY',

    CASE
        WHEN TX_COUNT >= 10 THEN 'CRITICAL'
        WHEN TX_COUNT >= 7 THEN 'HIGH'
        ELSE 'MEDIUM'
    END,

    LEAST(TX_COUNT * 10, 100),

    'Transactions in previous 15 minutes: '
    || TX_COUNT
    || '; Trigger transaction: '
    || TRANSACTION_ID

FROM velocity
WHERE TX_COUNT >= 5;

SELECT
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    CUSTOMER_ID,
    TRANSACTION_ID,
    SIGNAL_SCORE,
    EVIDENCE
FROM ANALYTICS.RISK_SIGNALS
ORDER BY SIGNAL_SCORE DESC;

USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;
USE WAREHOUSE RFR_WH;

INSERT INTO RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH historical_baseline AS (

    SELECT
        CUSTOMER_ID,
        AVG(AMOUNT) AS HISTORICAL_AVG,
        STDDEV_SAMP(AMOUNT) AS HISTORICAL_STDDEV,
        COUNT(*) AS HISTORICAL_COUNT
    FROM RFR_COPILOT.RAW.TRANSACTIONS
    WHERE TRANSACTION_ID NOT LIKE 'SC%'
    GROUP BY CUSTOMER_ID
),

candidate_transactions AS (

    SELECT
        t.TRANSACTION_ID,
        t.CUSTOMER_ID,
        t.ACCOUNT_ID,
        t.AMOUNT,
        h.HISTORICAL_AVG,
        h.HISTORICAL_STDDEV,
        h.HISTORICAL_COUNT,

        CASE
            WHEN h.HISTORICAL_STDDEV > 0 THEN
                ABS(
                    (t.AMOUNT - h.HISTORICAL_AVG)
                    / h.HISTORICAL_STDDEV
                )
            ELSE 0
        END AS Z_SCORE

    FROM RFR_COPILOT.RAW.TRANSACTIONS t

    JOIN historical_baseline h
        ON t.CUSTOMER_ID = h.CUSTOMER_ID

    WHERE t.TRANSACTION_ID LIKE 'SC%'
)

SELECT
    'AMT_' || TRANSACTION_ID AS SIGNAL_ID,

    CUSTOMER_ID,

    ACCOUNT_ID,

    TRANSACTION_ID,

    'AMOUNT_ANOMALY' AS SIGNAL_TYPE,

    CASE
        WHEN Z_SCORE >= 6 THEN 'CRITICAL'
        WHEN Z_SCORE >= 4 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS SIGNAL_SEVERITY,

    LEAST(100, ROUND(Z_SCORE * 10, 2)) AS SIGNAL_SCORE,

    'Current amount: '
    || ROUND(AMOUNT,2)
    || '; Historical average: '
    || ROUND(HISTORICAL_AVG,2)
    || '; Historical stddev: '
    || ROUND(HISTORICAL_STDDEV,2)
    || '; Historical transactions: '
    || HISTORICAL_COUNT
    || '; Z-score: '
    || ROUND(Z_SCORE,2)

FROM candidate_transactions

WHERE HISTORICAL_COUNT >= 10
  AND Z_SCORE >= 3;


SELECT
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    CUSTOMER_ID,
    TRANSACTION_ID,
    SIGNAL_SCORE,
    EVIDENCE
FROM ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'AMOUNT_ANOMALY'
ORDER BY SIGNAL_SCORE DESC;


/*
third signal: Structuring / near-threshold activity.
*/

USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;
USE WAREHOUSE RFR_WH;

INSERT INTO RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH near_threshold AS (

    SELECT
        t.TRANSACTION_ID,
        t.CUSTOMER_ID,
        t.ACCOUNT_ID,
        t.TRANSACTION_TIMESTAMP,
        t.AMOUNT,

        COUNT(*) OVER (
            PARTITION BY t.CUSTOMER_ID, t.ACCOUNT_ID
            ORDER BY t.TRANSACTION_TIMESTAMP
            RANGE BETWEEN INTERVAL '30 MINUTE' PRECEDING
                      AND CURRENT ROW
        ) AS NEAR_THRESHOLD_COUNT

    FROM RFR_COPILOT.RAW.TRANSACTIONS t

    WHERE t.AMOUNT >= 90000
      AND t.AMOUNT < 100000
)

SELECT
    'STR_' || TRANSACTION_ID AS SIGNAL_ID,

    CUSTOMER_ID,

    ACCOUNT_ID,

    TRANSACTION_ID,

    'STRUCTURING' AS SIGNAL_TYPE,

    CASE
        WHEN NEAR_THRESHOLD_COUNT >= 5 THEN 'CRITICAL'
        WHEN NEAR_THRESHOLD_COUNT >= 4 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS SIGNAL_SEVERITY,

    LEAST(
        100,
        NEAR_THRESHOLD_COUNT * 20
    ) AS SIGNAL_SCORE,

    'Near-threshold transactions: '
    || NEAR_THRESHOLD_COUNT
    || '; Threshold: 100000; Window: 30 minutes'
    || '; Trigger amount: '
    || ROUND(AMOUNT,2)

FROM near_threshold

WHERE NEAR_THRESHOLD_COUNT >= 3;

SELECT
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    CUSTOMER_ID,
    TRANSACTION_ID,
    SIGNAL_SCORE,
    EVIDENCE
FROM ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'STRUCTURING'
ORDER BY CUSTOMER_ID, TRANSACTION_ID;

/*

Geographic anomaly detector - 3 or more distinct transaction countries for the same customer within 60 minutes → geographic anomaly.

*/

USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;
USE WAREHOUSE RFR_WH;

INSERT INTO RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH geo_windows AS (

    SELECT
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,

        COUNT(DISTINCT t2.COUNTRY) AS DISTINCT_COUNTRIES_60M

    FROM RFR_COPILOT.RAW.TRANSACTIONS t1

    JOIN RFR_COPILOT.RAW.TRANSACTIONS t2
        ON t1.CUSTOMER_ID = t2.CUSTOMER_ID
       AND t2.TRANSACTION_TIMESTAMP
           BETWEEN DATEADD(
               MINUTE,
               -60,
               t1.TRANSACTION_TIMESTAMP
           )
           AND t1.TRANSACTION_TIMESTAMP

    GROUP BY
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY
)

SELECT
    'GEO_' || TRANSACTION_ID AS SIGNAL_ID,

    CUSTOMER_ID,

    ACCOUNT_ID,

    TRANSACTION_ID,

    'GEOGRAPHIC_ANOMALY' AS SIGNAL_TYPE,

    CASE
        WHEN DISTINCT_COUNTRIES_60M >= 4 THEN 'CRITICAL'
        ELSE 'HIGH'
    END AS SIGNAL_SEVERITY,

    CASE
        WHEN DISTINCT_COUNTRIES_60M >= 4 THEN 100
        ELSE 75
    END AS SIGNAL_SCORE,

    'Distinct countries in previous 60 minutes: '
    || DISTINCT_COUNTRIES_60M
    || '; Current country: '
    || COUNTRY
    || '; Transaction: '
    || TRANSACTION_ID

FROM geo_windows

WHERE DISTINCT_COUNTRIES_60M >= 3;


SELECT
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    CUSTOMER_ID,
    TRANSACTION_ID,
    SIGNAL_SCORE,
    EVIDENCE
FROM RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY'
ORDER BY CUSTOMER_ID, TRANSACTION_ID;

SELECT
    TRANSACTION_ID,
    TRANSACTION_TIMESTAMP,
    COUNTRY
FROM RFR_COPILOT.RAW.TRANSACTIONS
WHERE CUSTOMER_ID IN ('C00203','C00506')
  AND TRANSACTION_ID LIKE 'SC%'
ORDER BY CUSTOMER_ID, TRANSACTION_TIMESTAMP;


SELECT
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    CUSTOMER_ID,
    TRANSACTION_ID,
    SIGNAL_SCORE,
    EVIDENCE
FROM RFR_COPILOT.ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY'
  AND CUSTOMER_ID IN ('C00203','C00506')
ORDER BY CUSTOMER_ID, TRANSACTION_ID;

/*Insert behavioral signals*/

USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;
USE WAREHOUSE RFR_WH;

INSERT INTO RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH historical_daily AS (

    SELECT
        CUSTOMER_ID,
        DATE_TRUNC(
            'DAY',
            TRANSACTION_TIMESTAMP
        ) AS TX_DATE,

        SUM(AMOUNT) AS DAILY_AMOUNT

    FROM RFR_COPILOT.RAW.TRANSACTIONS

    WHERE TRANSACTION_ID NOT LIKE 'SC%'

    GROUP BY
        CUSTOMER_ID,
        DATE_TRUNC(
            'DAY',
            TRANSACTION_TIMESTAMP
        )
),

customer_behavior AS (

    SELECT
        CUSTOMER_ID,

        AVG(DAILY_AMOUNT) AS HISTORICAL_DAILY_AVG,

        STDDEV_SAMP(DAILY_AMOUNT) AS HISTORICAL_DAILY_STDDEV,

        COUNT(*) AS HISTORICAL_DAYS

    FROM historical_daily

    GROUP BY CUSTOMER_ID
),

scenario_daily AS (

    SELECT
        CUSTOMER_ID,

        ACCOUNT_ID,

        TRANSACTION_ID,

        TRANSACTION_TIMESTAMP,

        AMOUNT

    FROM RFR_COPILOT.RAW.TRANSACTIONS

    WHERE TRANSACTION_ID LIKE 'SC%'

),

behavior_scores AS (

    SELECT
        s.TRANSACTION_ID,
        s.CUSTOMER_ID,
        s.ACCOUNT_ID,
        s.AMOUNT,

        c.HISTORICAL_DAILY_AVG,
        c.HISTORICAL_DAILY_STDDEV,
        c.HISTORICAL_DAYS,

        CASE
            WHEN c.HISTORICAL_DAILY_STDDEV > 0
            THEN
                ABS(
                    (
                        s.AMOUNT
                        - c.HISTORICAL_DAILY_AVG
                    )
                    /
                    c.HISTORICAL_DAILY_STDDEV
                )
            ELSE 0
        END AS Z_SCORE

    FROM scenario_daily s

    JOIN customer_behavior c
        ON s.CUSTOMER_ID = c.CUSTOMER_ID
)

SELECT
    'BEH_' || TRANSACTION_ID AS SIGNAL_ID,

    CUSTOMER_ID,

    ACCOUNT_ID,

    TRANSACTION_ID,

    'BEHAVIORAL_ANOMALY' AS SIGNAL_TYPE,

    CASE
        WHEN Z_SCORE >= 6 THEN 'CRITICAL'
        WHEN Z_SCORE >= 4 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS SIGNAL_SEVERITY,

    LEAST(
        100,
        ROUND(Z_SCORE * 10, 2)
    ) AS SIGNAL_SCORE,

    'Current transaction amount: '
    || ROUND(AMOUNT,2)
    || '; Historical daily average: '
    || ROUND(HISTORICAL_DAILY_AVG,2)
    || '; Historical daily stddev: '
    || ROUND(HISTORICAL_DAILY_STDDEV,2)
    || '; Historical active days: '
    || HISTORICAL_DAYS
    || '; Behavioral z-score: '
    || ROUND(Z_SCORE,2)

FROM behavior_scores

WHERE HISTORICAL_DAYS >= 10
  AND Z_SCORE >= 3;


SELECT
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    CUSTOMER_ID,
    TRANSACTION_ID,
    SIGNAL_SCORE,
    EVIDENCE
FROM RFR_COPILOT.ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'BEHAVIORAL_ANOMALY'
ORDER BY SIGNAL_SCORE DESC;

USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;

DELETE FROM RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY';

INSERT INTO RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH geo_windows AS (

    SELECT
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,

        c.COUNTRY AS HOME_COUNTRY,

        COUNT(DISTINCT t2.COUNTRY) AS DISTINCT_COUNTRIES,

        COUNT(DISTINCT
            CASE
                WHEN t2.COUNTRY <> c.COUNTRY
                THEN t2.COUNTRY
            END
        ) AS NON_HOME_COUNTRIES

    FROM RFR_COPILOT.RAW.TRANSACTIONS t1

    JOIN RFR_COPILOT.RAW.CUSTOMERS c
        ON t1.CUSTOMER_ID = c.CUSTOMER_ID

    JOIN RFR_COPILOT.RAW.TRANSACTIONS t2
        ON t1.CUSTOMER_ID = t2.CUSTOMER_ID
       AND t1.ACCOUNT_ID = t2.ACCOUNT_ID
       AND t2.TRANSACTION_TIMESTAMP
           BETWEEN DATEADD(
               MINUTE,
               -40,
               t1.TRANSACTION_TIMESTAMP
           )
           AND t1.TRANSACTION_TIMESTAMP

    GROUP BY
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,
        c.COUNTRY
)

SELECT
    'GEO_' || TRANSACTION_ID,

    CUSTOMER_ID,

    ACCOUNT_ID,

    TRANSACTION_ID,

    'GEOGRAPHIC_ANOMALY',

    CASE
        WHEN NON_HOME_COUNTRIES >= 3 THEN 'CRITICAL'
        ELSE 'HIGH'
    END,

    CASE
        WHEN NON_HOME_COUNTRIES >= 3 THEN 100
        ELSE 75
    END,

    'Distinct countries in previous 40 minutes: '
    || DISTINCT_COUNTRIES
    || '; Non-home countries: '
    || NON_HOME_COUNTRIES
    || '; Home country: '
    || HOME_COUNTRY
    || '; Current country: '
    || COUNTRY
    || '; Transaction: '
    || TRANSACTION_ID

FROM geo_windows

WHERE DISTINCT_COUNTRIES >= 3
  AND NON_HOME_COUNTRIES >= 2;


SELECT
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
FROM RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY'
  AND CUSTOMER_ID IN ('C00203','C00506')
ORDER BY CUSTOMER_ID, TRANSACTION_ID;

SELECT
    t.TRANSACTION_ID,
    t.TRANSACTION_TIMESTAMP,
    t.AMOUNT,
    t.TRANSACTION_TYPE,
    t.CHANNEL,
    t.COUNTRY
FROM RFR_COPILOT.RAW.TRANSACTIONS t
WHERE t.CUSTOMER_ID = 'C00203'
  AND t.TRANSACTION_TIMESTAMP BETWEEN
      DATEADD(
          MINUTE,
          -40,
          (
              SELECT TRANSACTION_TIMESTAMP
              FROM RFR_COPILOT.RAW.TRANSACTIONS
              WHERE TRANSACTION_ID = 'TX000025202'
          )
      )
      AND
      (
          SELECT TRANSACTION_TIMESTAMP
          FROM RFR_COPILOT.RAW.TRANSACTIONS
          WHERE TRANSACTION_ID = 'TX000025202'
      )
ORDER BY t.TRANSACTION_TIMESTAMP;

DELETE FROM RFR_COPILOT.ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY';

INSERT INTO RFR_COPILOT.ANALYTICS.RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH geo_windows AS (

    SELECT
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,
        c.COUNTRY AS HOME_COUNTRY,

        COUNT(*) AS TRANSACTION_COUNT,

        COUNT(DISTINCT t2.COUNTRY) AS DISTINCT_COUNTRIES,

        COUNT(DISTINCT CASE
            WHEN t2.COUNTRY <> c.COUNTRY
            THEN t2.COUNTRY
        END) AS NON_HOME_COUNTRIES,

        COUNT_IF(
            t2.TRANSACTION_TYPE = 'TRANSFER'
        ) AS TRANSFER_COUNT,

        COUNT(DISTINCT t2.CHANNEL) AS CHANNEL_COUNT

    FROM RFR_COPILOT.RAW.TRANSACTIONS t1

    JOIN RFR_COPILOT.RAW.CUSTOMERS c
        ON t1.CUSTOMER_ID = c.CUSTOMER_ID

    JOIN RFR_COPILOT.RAW.TRANSACTIONS t2
        ON t1.CUSTOMER_ID = t2.CUSTOMER_ID
       AND t1.ACCOUNT_ID = t2.ACCOUNT_ID
       AND t2.TRANSACTION_TIMESTAMP BETWEEN
           DATEADD(MINUTE, -40, t1.TRANSACTION_TIMESTAMP)
           AND t1.TRANSACTION_TIMESTAMP

    GROUP BY
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,
        c.COUNTRY
)

SELECT
    'GEO_' || TRANSACTION_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    'GEOGRAPHIC_ANOMALY',

    CASE
        WHEN DISTINCT_COUNTRIES >= 3
         AND NON_HOME_COUNTRIES >= 3
        THEN 'CRITICAL'
        ELSE 'HIGH'
    END,

    CASE
        WHEN DISTINCT_COUNTRIES >= 3
         AND NON_HOME_COUNTRIES >= 3
        THEN 100
        ELSE 75
    END,

    'Distinct countries in previous 40 minutes: '
    || DISTINCT_COUNTRIES
    || '; Non-home countries: '
    || NON_HOME_COUNTRIES
    || '; Transfer transactions: '
    || TRANSFER_COUNT
    || '; Channel count: '
    || CHANNEL_COUNT
    || '; Home country: '
    || HOME_COUNTRY
    || '; Current country: '
    || COUNTRY
    || '; Transaction: '
    || TRANSACTION_ID

FROM geo_windows

WHERE DISTINCT_COUNTRIES >= 3
  AND NON_HOME_COUNTRIES >= 2
  AND TRANSACTION_COUNT >= 3
  AND TRANSFER_COUNT = TRANSACTION_COUNT
  AND CHANNEL_COUNT = 1;


SELECT
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
FROM RFR_COPILOT.ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY'
ORDER BY CUSTOMER_ID, TRANSACTION_ID;

SELECT
    COUNT(*) AS TOTAL_GEO_SIGNALS,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS_FLAGGED
FROM RFR_COPILOT.ANALYTICS.RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY';

USE DATABASE RFR_COPILOT;
USE SCHEMA ANALYTICS;

DELETE FROM RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY';




INSERT INTO RISK_SIGNALS (
    SIGNAL_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_TYPE,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
)

WITH geo_windows AS (

    SELECT
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,

        c.COUNTRY AS HOME_COUNTRY,

        COUNT(*) AS TRANSACTION_COUNT,

        COUNT(DISTINCT t2.COUNTRY) AS DISTINCT_COUNTRIES,

        COUNT(DISTINCT CASE
            WHEN t2.COUNTRY <> c.COUNTRY
            THEN t2.COUNTRY
        END) AS NON_HOME_COUNTRIES,

        COUNT_IF(
            t2.TRANSACTION_TYPE = 'TRANSFER'
        ) AS TRANSFER_COUNT,

        COUNT(DISTINCT t2.CHANNEL) AS CHANNEL_COUNT,

        SUM(t2.AMOUNT) AS WINDOW_AMOUNT

    FROM RFR_COPILOT.RAW.TRANSACTIONS t1

    JOIN RFR_COPILOT.RAW.CUSTOMERS c
        ON t1.CUSTOMER_ID = c.CUSTOMER_ID

    JOIN RFR_COPILOT.RAW.TRANSACTIONS t2
        ON t1.CUSTOMER_ID = t2.CUSTOMER_ID
       AND t1.ACCOUNT_ID = t2.ACCOUNT_ID
       AND t2.TRANSACTION_TIMESTAMP BETWEEN
           DATEADD(MINUTE, -40, t1.TRANSACTION_TIMESTAMP)
           AND t1.TRANSACTION_TIMESTAMP

    GROUP BY
        t1.TRANSACTION_ID,
        t1.CUSTOMER_ID,
        t1.ACCOUNT_ID,
        t1.TRANSACTION_TIMESTAMP,
        t1.COUNTRY,
        c.COUNTRY
)

SELECT
    'GEO_' || TRANSACTION_ID,

    CUSTOMER_ID,

    ACCOUNT_ID,

    TRANSACTION_ID,

    'GEOGRAPHIC_ANOMALY',

    CASE
        WHEN DISTINCT_COUNTRIES >= 3
         AND NON_HOME_COUNTRIES >= 3
        THEN 'CRITICAL'
        ELSE 'HIGH'
    END,

    CASE
        WHEN DISTINCT_COUNTRIES >= 3
         AND NON_HOME_COUNTRIES >= 3
        THEN 100
        ELSE 75
    END,

    'Distinct countries in previous 40 minutes: '
    || DISTINCT_COUNTRIES
    || '; Non-home countries: '
    || NON_HOME_COUNTRIES
    || '; Transactions: '
    || TRANSACTION_COUNT
    || '; Transfer transactions: '
    || TRANSFER_COUNT
    || '; Same channel: '
    || CHANNEL_COUNT
    || '; Window amount: '
    || ROUND(WINDOW_AMOUNT, 2)
    || '; Home country: '
    || HOME_COUNTRY
    || '; Current country: '
    || COUNTRY
    || '; Transaction: '
    || TRANSACTION_ID

FROM geo_windows

WHERE DISTINCT_COUNTRIES >= 3
  AND NON_HOME_COUNTRIES >= 2
  AND TRANSACTION_COUNT >= 3
  AND TRANSFER_COUNT = TRANSACTION_COUNT
  AND CHANNEL_COUNT = 1
  AND WINDOW_AMOUNT >= 80000;

SELECT
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_ID,
    SIGNAL_SEVERITY,
    SIGNAL_SCORE,
    EVIDENCE
FROM RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY'
ORDER BY CUSTOMER_ID, TRANSACTION_ID;

SELECT
    COUNT(*) AS TOTAL_GEO_SIGNALS,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS_FLAGGED
FROM RISK_SIGNALS
WHERE SIGNAL_TYPE = 'GEOGRAPHIC_ANOMALY';