USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS RFR_COPILOT;

CREATE SCHEMA IF NOT EXISTS RFR_COPILOT.RAW;
CREATE SCHEMA IF NOT EXISTS RFR_COPILOT.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS RFR_COPILOT.AI;

CREATE WAREHOUSE IF NOT EXISTS RFR_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE RFR_COPILOT;
USE WAREHOUSE RFR_WH;

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR(20),
    CUSTOMER_NAME VARCHAR(100),
    COUNTRY VARCHAR(50),
    CUSTOMER_TYPE VARCHAR(30),
    CUSTOMER_RISK_LEVEL VARCHAR(20),
    ANNUAL_INCOME NUMBER(15,2),
    CUSTOMER_SINCE DATE,
    KYC_STATUS VARCHAR(20),
    PEP_FLAG BOOLEAN
);

CREATE OR REPLACE TABLE RAW.ACCOUNTS (
    ACCOUNT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    ACCOUNT_TYPE VARCHAR(30),
    CURRENCY VARCHAR(10),
    OPEN_DATE DATE,
    BALANCE NUMBER(15,2),
    STATUS VARCHAR(20)
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
    TRANSACTION_ID VARCHAR(30),
    ACCOUNT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    AMOUNT NUMBER(15,2),
    CURRENCY VARCHAR(10),
    TRANSACTION_TYPE VARCHAR(30),
    CHANNEL VARCHAR(30),
    MERCHANT VARCHAR(100),
    COUNTRY VARCHAR(50)
);